# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github_client_id:           <%= ENV['GITHUB_CLIENT_ID']     %>
  github_client_secret:       <%= ENV['GITHUB_CLIENT_SECRET'] %>
  email_github_client_id:     <%= ENV['EMAIL_GITHUB_CLIENT_ID']     %>
  email_github_client_secret: <%= ENV['EMAIL_GITHUB_CLIENT_SECRET'] %>

development:
  <<: *default
  secret_key_base: 61979b4e37cb7a32b574cf290daa1dfaf8d51ad01e5caf9e42777abe713f8db530f856a849411c56d2b360bfb845bcb28cb256412a74c77f1bb816a4846b5b02

test:
  <<: *default
  secret_key_base: fe880565c459babe6434df46d41ceceba1374cc07c1690b0d5bb1d7f823ea04e87e0226d98e2f1d6afb9db4d61ceae34c57da67d9c4bc7c462a58e37406a0840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
